# Python Day 2

- recap 
- conditionals
- functions

Shift + Enter - run cell and move to next
Ctrl + Enter - run cell and stay in cell

In [1]:
name = "Raphaela" # string
age = 31 # integer
height = 160.5 # float

In [4]:
shopping_list = ["garlic", "onions", "cheese"]
print(shopping_list)

['garlic', 'onions', 'cheese']


In [5]:
shopping_list.append ("joghurt")
print(shopping_list)

['garlic', 'onions', 'cheese', 'joghurt']


In [6]:
shopping_list.pop(0)
print(shopping_list)

['onions', 'cheese', 'joghurt']


In [7]:
import numpy # numerical python
import matplotlib.pyplot as plt # plotting 
import glob # file collecting

In [9]:
data = numpy.loadtxt("data/inflammation-01.csv", delimiter=",")
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [10]:
print(numpy.mean(data))
print(numpy.min(data, axis=0))

6.14875
[0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3. 4. 5. 5. 5. 5. 4. 4. 4.
 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1. 0. 0. 0.]


In [11]:
data[0,:]

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [12]:
name[3:5]

'ha'

In [13]:
shopping_list

['onions', 'cheese', 'joghurt']

In [14]:
for ingredient in shopping_list:
    print(ingredient)

onions
cheese
joghurt


## Conditionals

In [15]:
num = 37
if num > 100:
    print("greater")
else:
    print("not greater")
print("done")

not greater
done


In [17]:
num = 53
print("before")
if num > 100:
    print("greater")
print("after")

before
after


In [20]:
num = 0 
if num > 0:
    print(num , "is positive")
elif num == 0:
    print(num, "is zero")
else:
    print(num, "is negative")

0 is zero


In [21]:
num = 3
if num > 0 and num < 6:
    print("between 0 and 6")
else:
    print("outside 0 and 6")

between 0 and 6


In [23]:
if (1 < 0) or (1 >= 0):
    print("at least one condition is true")

at least one condition is true


In [25]:
a = True # booleans
b = False

In [26]:
if a:
    print("a is true")

a is true


In [27]:
if "":
    print("empty string is true")
if "word":
    print("non-empty string is true")
if []:
    print("empty list is true")
if [1,2,3]:
    print("non-empty list is true")
if 0:
    print("zero is true")
if 1:
    print("one is true")

non-empty string is true
non-empty list is true
one is true


In [28]:
if not "":
    print("empty string is not true")

empty string is not true


In [32]:
if True | False:
    print("True") 

True


In [33]:
num = 3
if num != 5:
    print("something")
if not num == 5:
    print("something else")

something
something else


In [34]:
numbers = [1,2,3,4]
if 3 in numbers:
    print("3 is in numbers")

3 is in numbers


In [35]:
if 10 in numbers:
    print("10 is in numbers")

In [36]:
filenames =['inflammation-01.csv', 'myscript.py','inflammation-02.csv','small-01.csv','small-02.csv']

In [37]:
large_files = []
small_files = []
other_files = []
for filename in filenames:
    if filename.startswith("inflammation"):
        large_files.append(filename)
    elif filename.startswith("small"):
        small_files.append(filename)
    else:
        other_files.append(filename)
print("large", large_files)
print("small", small_files)
print("other", other_files)

large ['inflammation-01.csv', 'inflammation-02.csv']
small ['small-01.csv', 'small-02.csv']
other ['myscript.py']


In [38]:
for value in range(10):
    if value < 5:
        print(value)        

0
1
2
3
4


## Functions

In [39]:
def fahr_to_celsius(temp):
    return ((temp -32) * (5/9))

In [40]:
fahr_to_celsius(32)

0.0

In [41]:
print("boiling point of water", fahr_to_celsius(212), "C")

boiling point of water 100.0 C


In [42]:
def celsius_to_kelvin(temp_c):
    return temp_c + 273.15

print("freezing point of water in Kelvin:", celsius_to_kelvin(0))

freezing point of water in Kelvin: 273.15


In [43]:
def fahr_to_kelvin(temp_f):
    temp_c = fahr_to_celsius(temp_f)
    temp_k = celsius_to_kelvin(temp_c)
    return temp_k

In [44]:
print(fahr_to_kelvin(212.0))

373.15


In [45]:
def fahr_to_kelvin(temp_f):
    temp_c = fahr_to_celsius(temp_f)
    temp_k = celsius_to_kelvin(temp_c)
    return temp_k, temp_c

In [47]:
result = fahr_to_kelvin(212)

In [48]:
result[0]

373.15

In [49]:
result[1]

100.0

In [51]:
a, b = fahr_to_kelvin(212) 

In [52]:
print(a, b)

373.15 100.0


In [53]:
def fence(original, wrapper):
    return wrapper + original + wrapper

print(fence("name", "*"))

*name*


In [54]:
def add(a,b):
    print(a + b)

A = add(7,3)
print(A)

10
None


In [55]:
numpy.loadtxt("data/inflammation-01.csv", delimiter=",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [56]:
numpy.loadtxt("data/inflammation-01.csv", ",")

SyntaxError: unexpected EOF while parsing (<unknown>, line 1)

In [58]:
def offset_mean(data, target_mean_value=0.0):
    return (data - numpy.mean(data)) + target_mean_value

In [59]:
test_data = numpy.zeros((2,2))
print(offset_mean(test_data, 3))

[[3. 3.]
 [3. 3.]]


In [60]:
print(offset_mean(test_data))

[[0. 0.]
 [0. 0.]]


In [68]:
def a(b):
    """
    Converts Fahrenheit temperature to Kelvin.
    Input should be temp in fahrenheit. 
    ------
    Example:
    >>> a(212)
    sss
    """
    temp_c = fahr_to_celsius(temp_f)
    temp_k = celsius_to_kelvin(temp_k)
    return temp_k

In [69]:
help(a)

Help on function a in module __main__:

a(b)
    Converts Fahrenheit temperature to Kelvin.
    Input should be temp in fahrenheit. 
    ------
    Example:
    >>> a(212)
    sss



In [70]:
def outer(input_string):
    """
    Returns the first and last character of the string.
    ---
    Example:
    >>> outer("Helium")
    "Hm"
    """
    return input_string[0] + input_string[-1]

In [71]:
help(outer)

Help on function outer in module __main__:

outer(input_string)
    Returns the first and last character of the string.
    ---
    Example:
    >>> outer("Helium")
    "Hm"



In [72]:
outer("Helium")

'Hm'